// Generated by CoffeeScript 1.10.0
(function() {
  var $legend, ViewAllSeries, callCommon, callLegand, clickItem, finalEnergyId, highData, highlight, highlightLegend;

  highlightLegend = function(box_id, item, hide) {
    var legend_text;
    legend_text = "legend-item" + item;
    if (hide) {
      $("#" + box_id + " div." + legend_text).addClass('legend-show');
    } else {
      $("#" + box_id + " div." + legend_text).removeClass('legend-show');
    }
  };

  highlight = function(series, index, hide) {
    $(series).each(function(i, serie) {
      if (i !== index) {
        if (serie.type === "area") {
          serie.area.attr({
            opacity: (hide ? 0.25 : 0.75)
          });
        }
        if (serie.type === "column") {
          $.each(serie.data, function(k, data) {
            if (data.series) {
              data.graphic.attr({
                opacity: (hide ? 0.25 : 1)
              });
            }
          });
        }
        if (serie.type === "line") {
          $.each(serie.data, function(k, data) {
            if (data.series) {
              data.series.graph && data.series.graph.attr("stroke", (hide ? "#D4D4D4" : serie.color));
            }
          });
        }
      } else {
        if (serie.type === "area") {
          serie.area.attr({
            fill: serie.color
          });
          serie.area.attr({
            opacity: 1
          });
        }
        if (serie.type === "column") {
          $.each(serie.data, function(k, data) {
            if (data.series) {
              data.graphic.attr({
                opacity: 1
              });
            }
          });
        }
        if (serie.type === "line") {
          $.each(serie.data, function(k, data) {
            if (data.series) {
              data.series.graph && data.series.graph.attr("stroke", serie.color);
            }
          });
        }
      }
    });
  };

  highData = function(n, series, hide, name) {
    var Ddata, i;
    if (hide) {
      $("#display-data" + n + " #SeriesName").html(series.name);
      if (name !== 'Grid') {
        Ddata = [Highcharts.numberFormat(series.yData[0], 0, ","), Highcharts.numberFormat(series.yData[3], 0, ","), Highcharts.numberFormat(series.yData[5], 0, ","), Highcharts.numberFormat(series.yData[7], 0, ",")];
        i = 0;
        while (i < 4) {
          $("#display-data" + n + " #SeriesData" + i).html(Ddata[i]);
          i++;
        }
      }
    } else {
      i = 0;
      while (i < 4) {
        $("#display-data" + n + " #SeriesData" + i).empty();
        i++;
      }
      $("#display-data" + n + " #SeriesName").empty();
    }
  };

  clickItem = function(chartSeries, series, $legendItem, options, vCls) {
    chartSeries.forEach(function(seri) {
      seri.setVisible(false);
      if (seri.name === series.name) {
        seri.setVisible();
      } else {
        return;
      }
    });
    $('.' + vCls).css({
      display: "block"
    });
  };

  ViewAllSeries = function(chartSeries, vCls, va) {
    if (va == null) {
      va = null;
    }
    console.log(chartSeries);
    $.each(chartSeries, function(i, seri) {
      seri.setVisible(true);
    });
    $('.' + vCls).css({
      display: "none"
    });
  };

  callCommon = function(chartIdArr) {
    var $xData, i, parentElement, z;
    i = 0;
    while (i < chartIdArr.length) {
      parentElement = $(chartIdArr[i])[0];
      if (parentElement.children[0]) {
        finalEnergyId[i] = parentElement.children[0].id;
      }
      $("#custom-legend" + i).remove();
      $("#display-data" + i).remove();
      $xData = $("<div id=\"display-data" + i + "\">").css({
        width: "91%",
        marginLeft: 40,
        marginTop: 5,
        bottom: 0,
        height: 38
      }).appendTo(chartIdArr[i]);
      z = 0;
      while (z < 4) {
        $("<p id=\"SeriesData" + z + "\">").css({
          width: 43,
          paddingRight: 5,
          paddingLeft: 5,
          color: "#000",
          margin: 0,
          float: "left",
          fontWeight: "bold",
          fontSize: 10
        }).appendTo($xData);
        z++;
      }
      $("<p id='SeriesName'></p>").css({
        width: "100%",
        float: "left",
        fontWeight: "bold",
        textAlign: "center",
        lineHeight: "15px"
      }).appendTo($xData);
      $legend[i] = $("<div id=\"custom-legend" + i + "\" class=\"custom-legends\"><div class=\"view view" + i + "\">View All</div>").css({
        minWidth: "120px",
        borderRadius: "5px",
        boxShadow: "0 0 0 1px #ddd",
        maxHeight: "250px !important",
        overflow: "auto ",
        float: "left",
        backgroundColor: "#fff",
        top: "45px",
        left: "65px",
        opacity: "0.9",
        padding: "5px 5px 3px",
        position: "absolute",
        visibility: "hidden",
        transition: "visibility 0s linear 0.5s,opacity 0.5s linear"
      }).appendTo($("#" + finalEnergyId[i]));
      i++;
    }
  };

  callLegand = function(options0, chartSeries, l_index, chart_name) {
    $.each(chartSeries, function(i, series) {
      var $legendItem;
      if (series.name === 'Total demand' || series.name === 'Total supply' || series.name === 'Total') {
        $legendItem = $("<div class=\"legend-item" + series.index + "\">").css({
          position: "relative",
          paddingTo: 5,
          paddingBottom: 2
        }).css(options0[(series.visible ? "itemStyle" : "itemHiddenStyle")]).css({
          color: series.color,
          font: "normal 7pt sans-serif"
        }).html(series.name + '<div class="lin"></div>').appendTo($legend[l_index]);
      } else {
        $legendItem = $("<div class=\"legend-item" + series.index + "\">").css({
          position: "relative",
          paddingTo: 5,
          paddingBottom: 2
        }).css(options0[(series.visible ? "itemStyle" : "itemHiddenStyle")]).css({
          color: series.color,
          font: "normal 7pt sans-serif"
        }).html(series.name).appendTo($legend[l_index]);
      }
      $legendItem.click(function() {
        var vCls;
        vCls = 'view' + l_index;
        clickItem(chartSeries, series, $legendItem, options0, vCls);
      });
      $legendItem.hover((function() {
        $(this).css("fontWeight", "bold");
        highlight(chartSeries, series.index, true);
        highData(l_index, series, true, chart_name);
      }), function() {
        $(this).css("fontWeight", "normal");
        highlight(chartSeries, series.index, false);
        highData(l_index, series, false);
      });
    });
  };

  finalEnergyId = [];

  $legend = [];

  window.twentyfifty.highlightLegend = highlightLegend;

  window.twentyfifty.highlight = highlight;

  window.twentyfifty.highData = highData;

  window.twentyfifty.clickItem = clickItem;

  window.twentyfifty.ViewAllSeries = ViewAllSeries;

  window.twentyfifty.callCommon = callCommon;

  window.twentyfifty.callLegand = callLegand;

}).call(this);
